### ISSUE TITLE
Whether to base on libp2p,

### ISSUE THREAD

**Issue by huang12zheng** [wasm-peers/wasm-peers#2]
I am new to socket, and I am learning about video, including WebrTC
I think wasm, WebRTC, Rust are all great things.
But at the same time, I discovered libp2p.
```
A modular network stack.
Run your network applications free from runtime and address services, independently of their location.
```
I noticed that they seem to be adding webRTC (by the way, webRTC seems to be implemented on libp2p js)
* webrtc/: Add libp2p WebRTC specification
https://github.com/libp2p/specs/pull/412
* rust implementation
https://github.com/libp2p/rust-libp2p/pull/2622
> And now I see that it is going to reference https://github.com/webrtc-rs/webrtc
> ps, I didn't know webrtc-rs before

So,
1. what is wasm-peer different from WebRTC
2. Do you want to implement wasm-peer on libp2p?

**Comment by huang12zheng** [comment]
* Partial information supplement

```rust
struct WebRTC {}
struct WebRTCHandle {}
struct WebRTCHandleProp {}
impl IntoConnectionHandler for WebRTCHandleProp{}
impl ConnectionHandler for WebRTCHandle {}
impl NetworkBehaviour for WebRTC {}
```
The protocol provider implements these above.


> user want to Aspect of Webrtc Evnet, need to do
> impl NetworkBehaviourEventProcess<WebRTC> for XXX

```
let swarm = SwarmBuilder::new(transport, behaviour, peer_id).  // behaviour above define
swarm.poll_next_unpin(cx){}  // would inject process with derive expand
```

**Comment by tomkarw** [comment]
Hey @huang12zheng,
Rust, WASM and WebRTC are indeed all great things!

From what I understood, having done a very brief overview of `libp2p` is more of a specification, describing conventions to use while implementing peer-to-peer libraries and systems. This project, by depending on WebRTC, is strictly bound to their conventions and cannot override them.

To answer your questions:
1. `wasm-peer` is not different from WebRTC at all! It is a library on top of V8 (JavaScript engine) implementation of WebRTC Web API, that is easier to work with from Rust. It provides simpler API by constraining your choices and importantly provides a `signaling server` implementation, that is defined in WebRTC, but implementation is left up to the API user.
2. Given it is possible to use `wasm-peer` to implement peer-2-peer protocol compliant with `libp2p` specification, I'd love to see it. Unfortunately, I don't have enough incentive and bandwidth to do it. I would however advise you to give it a go yourself! You can use `wasm-peer` crate, and I'd be happy to guide you and implement missing features that would be required. Alternatively, you can write something new, by using this project as a guide (that's what I did with the two projects I list in the [acknowledgments](https://github.com/wasm-peers/wasm-peers#acknowledgments)).

**Comment by huang12zheng** [comment]
Sorry for the late reply, thank you for your explanation
I'm going to close it
